CREATE TABLE parks(
   ID        INTEGER  NOT NULL PRIMARY KEY 
  ,parkalias VARCHAR(85)
  ,parkkey   VARCHAR(5) NOT NULL
  ,parkname  VARCHAR(38) NOT NULL
  ,city      VARCHAR(16) NOT NULL
  ,state     VARCHAR(15)
  ,country   VARCHAR(2) NOT NULL
);
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (256,NULL,'ALB01','Riverside Park','Albany','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (257,NULL,'ALT01','Columbia Park','Altoona','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (258,'Edison Field; Anaheim Stadium','ANA01','Angel Stadium of Anaheim','Anaheim','CA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (259,NULL,'ARL01','Arlington Stadium','Arlington','TX','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (260,'The Ballpark in Arlington; Ameriquest Fl','ARL02','Rangers Ballpark in Arlington','Arlington','TX','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (261,NULL,'ATL01','Atlanta-Fulton County Stadium','Atlanta','GA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (262,NULL,'ATL02','Turner Field','Atlanta','GA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (263,NULL,'ATL03','Suntrust Park','Atlanta','GA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (264,NULL,'BAL01','Madison Avenue Grounds','Baltimore','MD','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (265,NULL,'BAL02','Newington Park','Baltimore','MD','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (266,NULL,'BAL03','Oriole Park I','Baltimore','MD','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (267,NULL,'BAL04','Belair Lot','Baltimore','MD','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (268,NULL,'BAL05','Monumental Park','Baltimore','MD','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (269,NULL,'BAL06','Oriole Park II','Baltimore','MD','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (270,NULL,'BAL07','Oriole Park III','Baltimore','MD','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (271,'American League Park','BAL09','Oriole Park IV','Baltimore','MD','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (272,'Oriole Park V','BAL10','Terrapin Park','Baltimore','MD','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (273,NULL,'BAL11','Memorial Stadium','Baltimore','MD','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (274,NULL,'BAL12','Oriole Park at Camden Yards','Baltimore','MD','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (275,'Walpole Street Grounds','BOS01','South End Grounds I','Boston','MA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (276,'Union Park','BOS02','Dartmouth Grounds','Boston','MA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (277,NULL,'BOS03','South End Grounds II','Boston','MA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (278,NULL,'BOS04','Congress Street Grounds','Boston','MA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (279,NULL,'BOS05','South End Grounds III','Boston','MA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (280,NULL,'BOS06','Huntington Avenue Baseball Grounds','Boston','MA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (281,NULL,'BOS07','Fenway Park','Boston','MA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (282,'Bee Hive','BOS08','Braves Field','Boston','MA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (283,NULL,'BUF01','Riverside Grounds','Buffalo','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (284,NULL,'BUF02','Olympic Park I','Buffalo','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (285,NULL,'BUF03','Olympic Park II','Buffalo','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (286,'Federal League Park','BUF04','International Fair Association Grounds','Buffalo','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (287,'Pastime Park','CAN01','Mahaffey Park','Canton','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (288,NULL,'CAN02','Pastime Park','Canton','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (289,'Union Base-ball Grounds','CHI01','Lake Front Park I','Chicago','IL','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (290,NULL,'CHI02','23rd Street Park','Chicago','IL','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (291,NULL,'CHI03','Lake Front Park II','Chicago','IL','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (292,'Cricket Club Grounds; Union Grounds','CHI05','South Side Park I','Chicago','IL','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (293,NULL,'CHI06','West Side Park','Chicago','IL','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (294,NULL,'CHI07','South Side Park II','Chicago','IL','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (295,NULL,'CHI08','West Side Grounds','Chicago','IL','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (296,NULL,'CHI09','South Side Park III','Chicago','IL','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (297,'White Sox Park','CHI10','Comiskey Park I','Chicago','IL','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (298,'Weeghman Park; Cubs Park','CHI11','Wrigley Field','Chicago','IL','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (299,'U.S. Cellular Field;White Sox Park; Comiskey Park II','CHI12','Guaranteed Rate Field','Chicago','IL','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (300,'Union Cricket Club Grounds','CIN01','Lincoln Park Grounds','Cincinnati','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (301,NULL,'CIN02','Avenue Grounds','Cincinnati','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (302,NULL,'CIN03','Bank Street Grounds','Cincinnati','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (303,NULL,'CIN04','League Park I','Cincinnati','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (304,NULL,'CIN05','League Park II','Cincinnati','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (305,'League Park III','CIN06','Palace of the Fans','Cincinnati','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (306,'Redland Field','CIN07','Crosley Field','Cincinnati','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (307,'Riverfront Stadium','CIN08','Cinergy Field','Cincinnati','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (308,NULL,'CIN09','Great American Ballpark','Cincinnati','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (309,NULL,'CLE01','National Association Grounds','Cleveland','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (310,'Kennard Street Park','CLE02','League Park I','Cleveland','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (311,'American Association Park','CLE03','League Park II','Cleveland','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (312,'Players League Park','CLE04','Brotherhood Park','Cleveland','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (313,'National League Park III','CLE05','League Park III','Cleveland','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (314,'Dunn Field','CLE06','League Park IV','Cleveland','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (315,'Municipal Stadium','CLE07','Cleveland Stadium','Cleveland','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (316,'Jacobs Field','CLE08','Progressive Field','Cleveland','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (317,NULL,'CLE09','Cedar Avenue Driving Park','Cleveland','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (318,NULL,'CLL01','Euclid Beach Park','Collinwood','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (319,NULL,'COL01','Recreation Park I','Columbus','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (320,NULL,'COL02','Recreation Park II','Columbus','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (321,NULL,'COL03','Neil Park I','Columbus','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (322,NULL,'COL04','Neil Park II','Columbus','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (323,NULL,'COV01','Star Baseball Park','Covington','KY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (324,NULL,'DAY01','Fairview Park','Dayton','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (325,NULL,'DEN01','Mile High Stadium','Denver','CO','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (326,NULL,'DEN02','Coors Field','Denver','CO','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (327,NULL,'DET01','Recreation Park','Detroit','MI','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (328,NULL,'DET02','Bennett Park','Detroit','MI','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (329,'West End Park','DET03','Burns Park','Detroit','MI','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (330,'Navin Field; Briggs Stadium','DET04','Tiger Stadium','Detroit','MI','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (331,NULL,'DET05','Comerica Park','Detroit','MI','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (332,NULL,'DOV01','Fairview Park Fair Grounds','Dover','DE','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (333,NULL,'ELM01','Maple Avenue Driving Park','Elmira','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (334,'Hamilton Field','FOR01','Grand Duchess','Fort Wayne','IN','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (335,NULL,'FOR03','Jailhouse Flats','Fort Wayne','IN','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (336,NULL,'FTB01','Fort Bragg Field','Fort Bragg','NC','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (337,'Beyerle''s Park','GEA01','Geauga Lake Grounds','Geauga Lake','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (338,NULL,'GLO01','Gloucester Point Grounds','Gloucester City','NJ','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (339,NULL,'GLO02','Gloucester Fireworks Park','Gloucester City','NJ','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (340,NULL,'GRA01','Ramona Park','Grand Rapids','MI','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (341,NULL,'HAR01','Harrison Field','Harrison','NJ','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (342,NULL,'HOB01','Elysian Field','Hoboken','NJ','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (343,NULL,'HON01','Aloha Stadium','Honolulu','HI','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (344,NULL,'HOU01','Colt Stadium','Houston','TX','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (345,NULL,'HOU02','Astrodome','Houston','TX','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (346,'Enron Field; Astros Field','HOU03','Minute Maid Park','Houston','TX','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (347,NULL,'HRT01','Hartford Ball Club Grounds','Hartford','CT','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (348,NULL,'HRT02','Hartford Trotting Park','Hartford','CT','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (349,NULL,'IND01','South Street Park','Indianapolis','IN','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (350,NULL,'IND02','Seventh Street Park I','Indianapolis','IN','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (351,NULL,'IND03','Bruce Grounds','Indianapolis','IN','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (352,NULL,'IND04','Seventh Street Park II','Indianapolis','IN','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (353,NULL,'IND05','Seventh Street Park III','Indianapolis','IN','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (354,NULL,'IND06','Indianapolis Park','Indianapolis','IN','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (355,'Washington Park','IND07','Federal League Park','Indianapolis','IN','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (356,NULL,'IRO01','Windsor Beach','Irondequoit','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (357,NULL,'JER01','Oakdale Park','Jersey City','NJ','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (358,NULL,'JER02','Roosevelt Stadium','Jersey City','NJ','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (359,NULL,'KAN01','Athletic Park','Kansas City','MO','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (360,NULL,'KAN02','Association Park','Kansas City','MO','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (361,NULL,'KAN03','Exposition Park','Kansas City','MO','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (362,NULL,'KAN04','Gordon and Koppel Field','Kansas City','MO','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (363,NULL,'KAN05','Municipal Stadium','Kansas City','MO','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (364,'Royals Stadium','KAN06','Kauffman Stadium','Kansas City','MO','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (365,'Walte''s Pasture','KEO01','Perry Park','Keokuk','IA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (366,NULL,'LAS01','Cashman Field','Las Vegas','NV','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (367,NULL,'LBV01','The Ballpark at Disney''s Wide World','Lake Buena Vista','FL','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (368,NULL,'LON01','London Stadium','London','ENG','UK');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (369,NULL,'LOS01','Los Angeles Memorial Coliseum','Los Angeles','CA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (370,NULL,'LOS02','Wrigley Field','Los Angeles','CA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (371,'Chavez Ravine','LOS03','Dodger Stadium','Los Angeles','CA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (372,NULL,'LOU01','Louisville Baseball Park','Louisville','KY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (373,NULL,'LOU02','Eclipse Park I','Louisville','KY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (374,NULL,'LOU03','Eclipse Park II','Louisville','KY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (375,NULL,'LOU04','Eclipse Park III','Louisville','KY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (376,NULL,'LUD01','Ludlow Baseball Park','Ludlow','KY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (377,NULL,'MAS01','Long Island Grounds','Maspeth','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (378,'JoeRobbie; ProPlayer; Dolphin; LandShark','MIA01','Sun Life Stadium','Miami','FL','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (379,NULL,'MIA02','Marlins Park','Miami','FL','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (380,NULL,'MID01','Mansfield Club Grounds','Middletown','CT','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (381,NULL,'MIL01','Milwaukee Base-Ball Grounds','Milwaukee','WI','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (382,NULL,'MIL02','Wright Street Grounds','Milwaukee','WI','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (383,NULL,'MIL03','Athletic Park','Milwaukee','WI','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (384,NULL,'MIL04','Lloyd Street Grounds','Milwaukee','WI','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (385,NULL,'MIL05','County Stadium','Milwaukee','WI','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (386,NULL,'MIL06','Miller Park','Milwaukee','WI','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (387,NULL,'MIN01','Athletic Park','Minneapolis','MN','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (388,NULL,'MIN02','Metropolitan Stadium','Bloomington','MN','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (389,NULL,'MIN03','Hubert H. Humphrey Metrodome','Minneapolis','MN','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (390,NULL,'MIN04','Target Field','Minneapolis','MN','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (391,NULL,'MNT01','Estadio Monterrey','Monterrey','Nuevo Leon','MX');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (392,'Jarry Park','MON01','Parc Jarry','Montreal','QC','CA');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (393,'Olympic Stadium','MON02','Stade Olympique','Montreal','QC','CA');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (394,'Brewster Park','NEW01','Howard Avenue Grounds','New Haven','CT','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (395,NULL,'NEW02','Hamilton Park','New Haven','CT','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (396,'Beyerle''s Park','NEW03','Geauga Lake Grounds','Geauga Lake','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (397,NULL,'NWK01','Wiedenmeyer''s Park','Newark','NJ','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (398,NULL,'NYC01','Union Grounds','Brooklyn','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (399,NULL,'NYC02','Capitoline Grounds','Brooklyn','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (400,NULL,'NYC03','Polo Grounds I (Southeast Diamond)','New York','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (401,NULL,'NYC04','Polo Grounds II (Southwest Diamond)','New York','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (402,NULL,'NYC05','Washington Park I','Brooklyn','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (403,NULL,'NYC06','Metropolitan Park','New York','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (404,'Ridgewood Park I','NYC07','Grauer''s Ridgewood Park','Queens','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (405,NULL,'NYC08','Washington Park II','Brooklyn','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (406,NULL,'NYC09','Polo Grounds III','New York','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (407,NULL,'NYC10','Polo Grounds IV','New York','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (408,NULL,'NYC11','Eastern Park','Brooklyn','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (409,NULL,'NYC12','Washington Park III','Brooklyn','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (410,NULL,'NYC13','Hilltop Park','New York','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (411,NULL,'NYC14','Polo Grounds V','New York','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (412,NULL,'NYC15','Ebbets Field','Brooklyn','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (413,NULL,'NYC16','Yankee Stadium I','New York','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (414,'William A. Shea Stadium','NYC17','Shea Stadium','New York','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (415,'Ridgewood Park II','NYC18','Wallace''s Ridgewood Park','Queens','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (416,NULL,'NYC19','Washington Park IV','Brooklyn','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (417,NULL,'NYC20','Citi Field','New York','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (418,NULL,'NYC21','Yankee Stadium II','New York','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (419,'Network Associates Coliseum','OAK01','Oakland-Alameda County Coliseum','Oakland','CA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (420,NULL,'OMA01','TD Ameritrade Park','Omaha','NE','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (421,'Pendleton Park','PEN01','East End Park','Cincinnati','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (422,'Athletics Park','PHI01','Jefferson Street Grounds','Philadelphia','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (423,NULL,'PHI02','Centennial Park','Philadelphia','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (424,NULL,'PHI03','Oakdale Park','Philadelphia','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (425,NULL,'PHI04','Recreation Park','Philadelphia','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (426,NULL,'PHI05','Keystone Park','Philadelphia','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (427,NULL,'PHI06','Huntingdon Grounds I','Philadelphia','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (428,NULL,'PHI07','Forepaugh Park','Philadelphia','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (429,NULL,'PHI08','University of Penn. Athletic Field','Philadelphia','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (430,NULL,'PHI09','Baker Bowl','Philadelphia','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (431,NULL,'PHI10','Columbia Park','Philadelphia','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (432,'Connie Mack Stadium','PHI11','Shibe Park','Philadelphia','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (433,NULL,'PHI12','Veterans Stadium','Philadelphia','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (434,NULL,'PHI13','Citizens Bank Park','Philadelphia','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (435,NULL,'PHI14','Huntingdon Grounds II','Philadelphia','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (436,'Bank One Ballpark','PHO01','Chase Field','Phoenix','AZ','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (437,NULL,'PIT01','Union Park','Pittsburgh','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (438,'Lower Field','PIT02','Exposition Park I','Pittsburgh','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (439,'Upper Field','PIT03','Exposition Park II','Pittsburgh','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (440,NULL,'PIT04','Recreation Park','Pittsburgh','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (441,NULL,'PIT05','Exposition Park III','Pittsburgh','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (442,NULL,'PIT06','Forbes Field','Pittsburgh','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (443,NULL,'PIT07','Three Rivers Stadium','Pittsburgh','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (444,NULL,'PIT08','PNC Park','Pittsburgh','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (445,NULL,'PRO01','Adelaide Avenue Grounds','Providence','RI','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (446,NULL,'PRO02','Messer Street Grounds','Providence','RI','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (447,NULL,'RCK01','Agricultural Society Fair Grounds','Rockford','IL','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (448,NULL,'RIC01','Richmond Fair Grounds','Richmond','VA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (449,NULL,'RIC02','Allens Pasture','Richmond','VA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (450,NULL,'ROC01','Culver Field I','Rochester','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (451,NULL,'ROC02','Culver Field II','Rochester','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (452,NULL,'ROC03','Ontario Beach Grounds','Rochester','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (453,NULL,'SAI01','St. George Cricket Grounds','New York','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (454,'San Diego/Jack Murphy Stadium','SAN01','Qualcomm Stadium','San Diego','CA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (455,NULL,'SAN02','PETCO Park','San Diego','CA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (456,NULL,'SEA01','Sick''s Stadium','Seattle','WA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (457,NULL,'SEA02','Kingdome','Seattle','WA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (458,'T-Mobile Park','SEA03','Safeco Field','Seattle','WA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (459,NULL,'SFO01','Seals Stadium','San Francisco','CA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (460,'3Com Park','SFO02','Candlestick Park','San Francisco','CA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (461,'Pacific Bell Park; SBC Park','SFO03','AT&T Park','San Francisco','CA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (462,NULL,'SJU01','Estadio Hiram Bithorn','San Juan',NULL,'PR');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (463,'Springfield Track','SPR01','Hampden Park Race Track','Springfield','MA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (464,NULL,'STL01','Red Stockings Base Ball Park','St. Louis','MO','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (465,NULL,'STL02','Grand Avenue Park','St. Louis','MO','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (466,NULL,'STL03','Sportsman''s Park I','St. Louis','MO','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (467,NULL,'STL04','Union Grounds','St. Louis','MO','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (468,NULL,'STL05','Robison Field','St. Louis','MO','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (469,NULL,'STL06','Sportsman''s Park II','St. Louis','MO','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (470,'Busch Stadium I','STL07','Sportsman''s Park III','St. Louis','MO','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (471,'Federal League Park','STL08','Handlan''s Park','St. Louis','MO','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (472,NULL,'STL09','Busch Stadium II','St. Louis','MO','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (473,NULL,'STL10','Busch Stadium III','St. Louis','MO','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (474,NULL,'STP01','Tropicana Field','St. Petersburg','FL','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (475,NULL,'SYD01','Sydney Cricket Ground','Sydney','New South Wales','AU');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (476,'Newell Park','SYR01','Star Park I','Syracuse','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (477,NULL,'SYR02','Star Park II','Syracuse','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (478,NULL,'SYR03','Iron Pier','Syracuse','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (479,NULL,'THR01','Three Rivers Park','Three Rivers','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (480,NULL,'TOK01','Tokyo Dome','Tokyo','Tokyo','JP');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (481,NULL,'TOL01','League Park','Toledo','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (482,NULL,'TOL02','Tri-State Fair Grounds','Toledo','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (483,NULL,'TOL03','Speranza Park','Toledo','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (484,NULL,'TOL04','Armory Park','Toledo','OH','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (485,NULL,'TOR01','Exhibition Stadium','Toronto','ON','CA');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (486,'Skydome','TOR02','Rogers Centre','Toronto','ON','CA');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (487,NULL,'TRO01','Haymakers'' Grounds','Troy','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (488,NULL,'TRO02','Putnam Grounds','Troy','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (489,NULL,'WAR01','Rocky Point Park','Warwick','RI','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (490,NULL,'WAS01','Olympic Grounds','Washington','DC','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (491,NULL,'WAS02','National Grounds','Washington','DC','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (492,NULL,'WAS03','Capitol Grounds','Washington','DC','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (493,NULL,'WAS04','Athletic Park','Washington','DC','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (494,NULL,'WAS05','Swampoodle Grounds','Washington','DC','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (495,NULL,'WAS06','Boundary Field','Washington','DC','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (496,NULL,'WAS07','American League Park I','Washington','DC','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (497,NULL,'WAS08','American League Park II','Washington','DC','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (498,NULL,'WAS09','Griffith Stadium','Washington','DC','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (499,'D.C. Stadium','WAS10','Robert F. Kennedy Stadium','Washington','DC','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (500,NULL,'WAS11','Nationals Park','Washington','DC','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (501,NULL,'WAT01','Troy Ball Club Grounds','Watervliet','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (502,NULL,'WAV01','Waverly Fairgrounds','Waverly','NJ','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (503,NULL,'WEE01','Monitor Grounds','Weehawken','NJ','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (504,NULL,'WHE01','Island Grounds','Wheeling','WV','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (505,NULL,'WIL01','Union Street Park','Wilmington','DE','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (506,NULL,'WIL02','BB&T Ballpark at Bowman Field','Williamsport','PA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (507,NULL,'WNY01','West New York Field Club Grounds','West New York','NJ','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (508,NULL,'WOR01','Agricultural County Fair Grounds I','Worcester','MA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (509,NULL,'WOR02','Agricultural County Fair Grounds II','Worcester','MA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (510,NULL,'WOR03','Worcester Driving Park Grounds','Worcester','MA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (511,'Estadio Alfredo Harp Hel�','MEX02','Alfredo Harp Hel� Stadium','Mexico City','CDMX','MX');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (512,NULL,'DYE01','Field of Dreams','Dyersville','IA','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (513,'Dunedin Stadium at Grant Field; Knology Park; Florida Auto Exchange Stadium','DUN01','TD Ballpark','Dunedin','FL','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (514,'Pilot Field; Downtown Ballpark; North AmeriCare Park; Dunn Tire Park; Coca-Cola Field','BUF05','Sahlen Field','Buffalo','NY','US');
INSERT INTO parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (515,NULL,'ARL03','Field of Dreams','Arlington','TX','US');
