# Generated by Django 5.1.7 on 2025-03-08 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('given_name', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('deathdate', models.DateField(null=True)),
                ('batting_hand', models.CharField(max_length=1, null=True)),
                ('throwing_hand', models.CharField(max_length=1, null=True)),
                ('birth_city', models.CharField(max_length=50, null=True)),
                ('birth_state', models.CharField(max_length=50, null=True)),
                ('birth_country', models.CharField(max_length=50, null=True)),
                ('first_game', models.DateField(null=True)),
                ('last_game', models.DateField(null=True)),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='PlayerSeason',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('games_played', models.IntegerField(null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='mlb_data.player')),
            ],
            options={
                'db_table': 'player_season',
                'unique_together': {('player', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PitchingStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('outs_pitched', models.IntegerField(null=True)),
                ('earned_runs_allowed', models.IntegerField(null=True)),
                ('home_runs_allowed', models.IntegerField(null=True)),
                ('strikeouts', models.IntegerField(null=True)),
                ('walks', models.IntegerField(null=True)),
                ('wins', models.IntegerField(null=True)),
                ('losses', models.IntegerField(null=True)),
                ('wild_pitches', models.IntegerField(null=True)),
                ('batters_faced', models.IntegerField(null=True)),
                ('hit_batters', models.IntegerField(null=True)),
                ('saves', models.IntegerField(null=True)),
                ('player_season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pitching_stats', to='mlb_data.playerseason')),
            ],
            options={
                'db_table': 'pitching_stats',
            },
        ),
        migrations.CreateModel(
            name='FieldingStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('errors', models.IntegerField(null=True)),
                ('put_outs', models.IntegerField(null=True)),
                ('player_season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fielding_stats', to='mlb_data.playerseason')),
            ],
            options={
                'db_table': 'fielding_stats',
            },
        ),
        migrations.CreateModel(
            name='CatchingStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('passed_balls', models.IntegerField(null=True)),
                ('wild_pitches', models.IntegerField(null=True)),
                ('steals_allowed', models.IntegerField(null=True)),
                ('steals_caught', models.IntegerField(null=True)),
                ('player_season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catching_stats', to='mlb_data.playerseason')),
            ],
            options={
                'db_table': 'catching_stats',
            },
        ),
        migrations.CreateModel(
            name='BattingStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('at_bats', models.IntegerField(null=True)),
                ('hits', models.IntegerField(null=True)),
                ('doubles', models.IntegerField(null=True)),
                ('triples', models.IntegerField(null=True)),
                ('home_runs', models.IntegerField(null=True)),
                ('runs_batted_in', models.IntegerField(null=True)),
                ('strikeouts', models.IntegerField(null=True)),
                ('walks', models.IntegerField(null=True)),
                ('hits_by_pitch', models.IntegerField(null=True)),
                ('intentional_walks', models.IntegerField(null=True)),
                ('steals', models.IntegerField(null=True)),
                ('steals_attempted', models.IntegerField(null=True)),
                ('player_season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batting_stats', to='mlb_data.playerseason')),
            ],
            options={
                'db_table': 'batting_stats',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='positions',
            field=models.ManyToManyField(to='mlb_data.position'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('name', 'birthdate')},
        ),
    ]
